logging:
  level:
    org.springframework: error
    org.springframework.security: debug


spring:
  data:
    cassandra:
      keyspace-name: th_auth
      contact-points: localhost
      port: 9042
      schema-action: create_if_not_exists
